apiVersion: v1

kind: pod

metadata:
  name: myapp-pod
  label:
    tier: frontend

spec:
  containers:
    - name: nginx-container
      image: nginx

  nodeSelector:
    size: Large

  affinity:
    nodeAffinity:
      requiredDurignSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - Large
# kubectl label nodes node-1 size=Large
