apiVersion: v1

kind: pod

metadata:
  name: myapp-pod
  label:
    tier: frontend

spec:
  containers:
    - name: nginx-container
      image: nginx

  tolerations:
    - key: 'app'
      operator: 'Equal'
      value: 'blue'
      effect: 'NoSchedule'
# kubectl taint nodes node1 app=blue:NoSchedule
# kubectl taint nodes node1 app=blue:NoSchedule-
# kubectl get pods --selector tier=frontend
# kubectl describe node kubemaster | grep Taint
