# openssl genrsa -out jane.key 2048
# openssl req -new -key jane.key -subj "/CN=jane" -out jane.csr
#
#

apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups:
    - system:authenticated
  usages:
    - digital signatur
    - key encipherment
    - server auth
  request:
    # cat jane.csr | base64
# kubectl get csr
# kubectl get csr jane -o yaml <-- base64 encoded!
# kubectl certificate approve jane
