apiVersion: v1
kind: Config

clusters:
  - name: my-kube-playground
    cluster:
      certificate-authority: ca.crt
      server: https://my-kube-playground:6443

contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
      #namespace: optionalNamespace

users:
  - name: my-kube-admin
    user:
      client-certificate: admin.crt # better: fullpath
      # alternative: certificate-authority-data: cat admin.crt | base64
      client-clie: admin.key
# kubectl config view
# kubectl config use-context prod-user@production
# --kubeconfig
