apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    ### This is just the pod ###s
    metadata:
      name: myapp-pod
      label:
        app: myapp
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx
  #Replicaset will be created
  replicas: 3

  selector:
    matchLabels:
      type: front-end
# kubectl create -f <FILENAME>
# kubectl get deployments
# kubectl delete deployment <REPLICASET_NAME> <-- Also deletes underlying pods
# kubectl replace -f <FILENAME>
# kubectl scale --replicas=6 -f <FILENAME>
