apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
# kubectl exec -it hr -- nslookup mysql.payroll > /root/CKA/nslookup.out
# kubectl run nginx-pod --image=nginx:alpine -l tier=msg
# STATIC PODS: kubectl run --restart=Never --image=busybox static-busybox --dry-run -o yaml --command -- sleep 1000 > /etc/kubernetes/manifests/static-busybox.yaml
## cd /var/lib/kubelet
## grep -i staticPod config.yaml
