apiVersion: v1

kind: pod

metadata:
  name: myapp-pod
  label:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
# kubectl exec -it hr -- nslookup mysql.payroll > /root/CKA/nslookup.out
