apiVersion: v1
kind: ReplicationController
medata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    ### This is just the pod ###s
    metadata:
      name: myapp-pod
      label:
        app: myapp

    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3
