apiVersion: v1
kind: Service
metadata:
  name: backe-end

spec:
  type: ClusterIP # default
  ports:
    - targetPort: 80
      port: 80 # default = targetPort
  selector:
    app: myapp # from pod-definition-file
    type: front-end # from pod-definition-file

# kubectl create -f <FILENAME>
# kubectl get services
# curl <CLUSTER_IP>:30008
