apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod
# kubectl create configmap \
#     app-config --from-literal=APP_MOD=prod
#   OR app-config --from-file=app_cinfig.properties
# kubectl get configmaps
# kubectl get configmap <NAME>
