apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: mysql # this should be stored as base64 encoded
  DB_USER: root # this should be stored as base64 encoded
  DB_PASSWORD: passwrd # this should be stored as base64 encoded

# kubectl creacte secret generic \
#     app-secret --from-literal=DB_HOST=mysql
#   OR app-secret --from-file=app_secret.properties

# kubectl get secrets
# kubectl describe secrets
# kubectl get secret app-secret -o yaml

# envFrom
# - secretRef:
#     name: mysecret
